let game = new Game([
    {word: 'tomate', incorrect: ['animal', 'cuadrado', 'lento'], correct: 'rojo'},
    {word: 'rojo', incorrect: ['limón', 'lento', 'pariente'], correct: 'amarillo'},
    {word: 'amarillo', incorrect: ['hermano', 'rápido', 'agua'], correct: 'plátano'},
    {word: 'plátano', incorrect: ['color', 'animal', 'rápido'], correct: 'alimento'},
    {word: 'alimento', incorrect: ['rodilla', 'segundo', 'chaqueta'], correct: 'leche'},
    {word: 'leche', incorrect: ['chorizo', 'sólido', 'hermoso'], correct: 'queso'},
    {word: 'queso', incorrect: ['naranja', 'zapato', 'delante'], correct: 'mantequilla'},
    {word: 'mantequilla', incorrect: ['cabeza', 'rápida', 'herramienta'], correct: 'blanda'},
    {word: 'blanda', incorrect: ['piedra', 'escalera', 'tijera'], correct: 'almohada'},
    {word: 'almohada', incorrect: ['cocinar', 'caminar', 'trabajar'], correct: 'dormir'},
    {word: 'dormir', incorrect: ['volar', 'correr', 'comprar'], correct: 'descansar'},
    {word: 'descansar', incorrect: ['atado', 'mojado', 'enfadado'], correct: 'sentado'},
    {word: 'sentado', incorrect: ['zapato', 'pala', 'guante'], correct: 'sofá'},
    {word: 'sofá', incorrect: ['garaje', 'puente', 'parque'], correct: 'habitación'},
    {word: 'habitación', incorrect: ['autobús', 'granja', 'canción'], correct: 'vivienda'},
    {word: 'vivienda', incorrect: ['tractor', 'cocodrilo', 'semáforo'], correct: 'nevera'},
    {word: 'nevera', incorrect: ['libro', 'caliente', 'chaqueta'], correct: 'manzana'},
    {word: 'manzana', incorrect: ['bebida', 'carne', 'medicina'], correct: 'fruta'},
    {word: 'fruta', incorrect: ['judía', 'espárrago', 'sardina'], correct: 'uva'},
    {word: 'uva', incorrect: ['sopa', 'café', 'cerveza'], correct: 'vino'},
    {word: 'vino', incorrect: ['cuchillo', 'jabón', 'plato'], correct: 'botella'},
    {word: 'botella', incorrect: ['metro', 'madera', 'coche'], correct: 'frágil'},
    {word: 'frágil', incorrect: ['fuerte', 'arena', 'hierro'], correct: 'cristal'},
    {word: 'cristal', incorrect: ['puerto', 'carretera', 'antena'], correct: 'ventana'},
    {word: 'ventana', incorrect: ['baldosa', 'suelo', 'cable'], correct: 'puerta'},
    {word: 'puerta', incorrect: ['enferma', 'sabrosa', 'dormida'], correct: 'abierta'},
    {word: 'abierta', incorrect: ['luna', 'sombra', 'recta'], correct: 'boca'},
    {word: 'boca', incorrect: ['pelo', 'silla', 'radio'], correct: 'diente'},
    {word: 'diente', incorrect: ['sano','cansado', 'patata'], correct: 'comestible'},

    {word: 'caracol', incorrect: ['rápido', 'salvaje', 'peligroso'], correct: 'lento'},
    {word: 'lento', incorrect: ['tren', 'ratón', 'avión'], correct: 'anciano'},
    {word: 'anciano', incorrect: ['menor', 'empezar', 'nacer'], correct: 'mayor'},
    {word: 'mayor', incorrect: ['80', '44', '12'], correct: '88'},
    {word: '88', incorrect: ['impar', 'dividir', 'soplar'], correct: 'par'},
    {word: 'par', incorrect: ['nariz', 'luna', 'respirar'], correct: 'zapatos'},
    {word: 'zapatos', incorrect: ['sombrero', 'comer', 'animal'], correct: 'calcetines'},
    {word: 'calcetines', incorrect: ['manos', 'pelo', 'caballo'], correct: 'pies'},
    {word: 'pies', incorrect: ['pensar', 'pez', 'cocinar'], correct: 'caminar'},
    {word: 'caminar', incorrect: ['mar', 'pared', 'nube'], correct: 'acera'},
    {word: 'acera', incorrect: ['vela', 'río', 'playa'], correct: 'calle'},
    {word: 'calle', incorrect: ['desnudo', 'león', 'dentro'], correct: 'farola'},
    {word: 'farola', incorrect: ['espalda', 'dentro', 'árbol'], correct: 'luz'},
    {word: 'luz', incorrect: ['despacio', 'manos', 'negro'], correct: 'bombilla'},
    {word: 'bombilla', incorrect: ['correr', 'soñar', 'abrir'], correct: 'apagar'},
    {word: 'apagar', incorrect: ['cerradura', 'candado', 'dinero'], correct: 'interruptor'},
    {word: 'interruptor', incorrect: ['carpintero', 'pintor', 'profesor'], correct: 'electricista'},
    {word: 'electricista', incorrect: ['caballo', 'anciano', 'acabado'], correct: 'mecánico'},
    {word: 'mecánico', incorrect: ['comida', 'vendedor', 'mesa'], correct: 'motor'},
    {word: 'motor', incorrect: ['silencio', 'golosina', 'doctor'], correct: 'gasolina'},
    {word: 'gasolina', incorrect: ['lento', 'gaseoso', 'alumno'], correct: 'líquido'},
    {word: 'líquido', incorrect: ['morir', 'rápido', 'hielo'], correct: 'agua'},
    {word: 'agua', incorrect: ['sombra', 'tenedor', 'arena'], correct: 'lluvia'},
    {word: 'lluvia', incorrect: ['sol', 'barco', 'piedra'], correct: 'barro'},
    {word: 'barro', incorrect: ['cortar', 'planchar', 'salir'], correct: 'ensuciar'},
    {word: 'ensuciar', incorrect: ['nevera', 'televisión', 'ventilador'], correct: 'lavadora'},
    {word: 'lavadora', incorrect: ['molesta', 'transporte', 'alimentación'], correct: 'eléctrica'},
    {word: 'eléctrica', incorrect: ['cuchara', 'escoba', 'servilleta'], correct: 'cocina'},
    {word: 'cocina', incorrect: ['llegada', 'vestido', 'fuera'], correct: 'comida'},
    
    {word: 'arriba', incorrect: ['debajo', 'pozo', 'dentro'], correct: 'tejado'},
    {word: 'tejado', incorrect: ['sombrero', 'cabeza', 'mojado'], correct: 'chimenea'},
    {word: 'chimenea', incorrect: ['viento', 'frío', 'lluvia'], correct: 'humo'},
    {word: 'humo', incorrect: ['zumo', 'niebla', 'manta'], correct: 'fuego'},
    {word: 'fuego', incorrect: ['largo', 'color', 'luego'], correct: 'calor'},
    {word: 'calor', incorrect: ['azul', 'corto', 'sabor'], correct: 'verano'},
    {word: 'verano', incorrect: ['blanco', 'martes', 'enero'], correct: 'otoño'},
    {word: 'otoño', incorrect: ['después', 'año', 'gramo'], correct: 'estación'},
    {word: 'estación', incorrect: ['ascensor','hospital', 'debajo'], correct: 'autobús'},
    {word: 'autobús', incorrect: ['volar', 'platos','cuaderno'], correct: 'ruedas'},
    {word: 'ruedas', incorrect: ['ninguna', 'cuerdas', 'cuadradas'], correct: 'redondas'},
    {word: 'redondas', incorrect: ['piedras', 'demasiadas', 'medianas'], correct: 'monedas'},
    {word: 'monedas', incorrect: ['plástico', 'cartón', 'papel'], correct: 'metal'},
    {word: 'metal', incorrect: ['árbol', 'traje', 'sombrero'], correct: 'motor'},
    {word: 'motor', incorrect: ['sudar', 'escribir', 'cocinar'], correct: 'arrancar'},
    {word: 'arrancar', incorrect: ['río', 'aparcar', 'nube'], correct: 'muela'},
    {word: 'muela', incorrect: ['revista', 'espalda', 'albañil'], correct: 'dentista'},
    {word: 'dentista', incorrect: ['solista', 'ciclista', 'lista'], correct: 'oculista'},
    {word: 'oculista', incorrect: ['esconder', 'conductor', 'cocinero'], correct: 'gafas'},
    {word: 'gafas', incorrect: ['subir', 'oír', 'salir'], correct: 'ver'},
    {word: 'ver', incorrect: ['orejas', 'pelo', 'nariz'], correct: 'ojos'},
    {word: 'ojos', incorrect: ['sudar', 'beber', 'escupir'], correct: 'abrir'},
    {word: 'abrir', incorrect: ['subir', 'sombra', 'llorar'], correct: 'grifo'},
    {word: 'grifo', incorrect: ['comer', 'freír', 'respirar'], correct: 'comprar'},
    {word: 'comprar', incorrect: ['sano', 'sucio', 'lento'], correct: 'caro'},
    {word: 'caro', incorrect: ['vecino', 'enemigo', 'limpio'], correct: 'dinero'},
    {word: 'dinero', incorrect: ['primero', 'cielo', 'blanco'], correct: 'banco'},
    {word: 'banco', incorrect: ['escalera', 'lapicero', 'bicicleta'], correct: 'parque'},
    {word: 'parque', incorrect: ['puerta', 'tren', 'moto'], correct: 'jardin'},
])
document.querySelector('.DH_play-button').addEventListener('click', (event) => {
    document.querySelector('.DH_instructions').style.display = 'none'
})
game.start()